IP=${1}

(cat <<_EOF
# Generated by iptables-save v1.8.4 on Thu Sep 17 06:12:21 2020
*nat
:PREROUTING ACCEPT [11445:672121]
:INPUT ACCEPT [11385:668521]
:OUTPUT ACCEPT [18147:1353007]
:POSTROUTING ACCEPT [18147:1353007]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
COMMIT
# Completed on Thu Sep 17 06:12:21 2020
# Generated by iptables-save v1.8.4 on Thu Sep 17 06:12:21 2020
*filter
:INPUT ACCEPT [1615:385675]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [2050:572005]
:DOCKER - [0:0]
:DOCKER-ISOLATION-STAGE-1 - [0:0]
:DOCKER-ISOLATION-STAGE-2 - [0:0]
:DOCKER-USER - [0:0]
-A INPUT -s ${IP}/32 -p tcp -m tcp --dport 6018 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 6018 -j DROP
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
COMMIT
# Completed on Thu Sep 17 06:12:21 2020
_EOF
) > /etc/iptables/rules.v4


iptables-restore  < /etc/iptables/rules.v4
